services:
  ecommerce-whatsapp-postgres:
    image: postgres:17
    restart: always
    volumes:
        - "ecommerce-whatsapp-db:/var/lib/postgresql/data"
    ports:
        - "54355:5432"
    env_file:
      - .env

volumes:
  ecommerce-whatsapp-db:
    external: true
