services:
  lunatv-postgres:
    image: postgres:17
    restart: always
    volumes:
        - "lunatv-db:/var/lib/postgresql/data"
    ports:
        - "5435:5432"
    env_file:
      - .env

volumes:
  lunatv-db:
    external: true
